name: Github Actions Demo
on: 
  push:
    branches:
      - main
      - feature/**
      - 'release/**'
  pull_request:
    types: 
      - opened
    branches:
      - main
jobs:
  actions-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Print about.jsx file
        uses: cat src/about.jsx

      - name: Print Variables and secrets
        run: |
          echo "A demo build, ${{ vars.MY_NAME }}"
          echo "A demo build ${{ secrets.DOCKER_PASSWORD }}"

